### ISSUE TITLE
install setup fails

### ISSUE THREAD

**Issue by Borda** [automl/HPOlib#121]
it fails to install via pip using python3.x as `pip3 install git+https://github.com/automl/HPOlib.git`

```
Collecting git+https://github.com/automl/HPOlib.git (from -r requirements.txt (line 18))
  Cloning https://github.com/automl/HPOlib.git to /tmp/pip-req-build-pv5izw4g
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-pv5izw4g/setup.py", line 54
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
```

**Comment by KEggensperger** [comment]
This package does not support python3.x, so pip3 won't work.
